site_name: Predbat Documentation
theme:
  name: readthedocs
nav:
  - Introduction: index.md
  - 'What does Predbat do?': what-does-predbat-do.md
  - 'Words of caution': caution.md
  - 'Installing & configuring Predbat':
    - 'Install summary': installation-summary.md
    - 'Install details': install.md
    - inverter-setup.md
    - energy-rates.md
    - apps-yaml.md
    - car-charging.md
    - configuration-guide.md
    - customisation.md
    - video-guides.md
    - faq.md
    - devices.md
    - manual-api.md
  - 'Viewing Predbat data':
    - output-data.md
    - web-interface.md
    - predbat-plan-card.md
    - creating-charts.md
    - compare.md
  - 'Predbat development':
    - todo-list.md
    - developing.md
    - rest_api.md
    - plugin.md
  - 'Predheat':
    - predheat.md
markdown_extensions:
  - sane_lists
